
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Apr 30 11:04:05 MST 2022
//----------------------------------------------------

package Codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Estatico = 37;
  public static final int Numero_Decimal = 50;
  public static final int Op_Logicos = 8;
  public static final int Coma = 21;
  public static final int Llave_c = 17;
  public static final int Llave_a = 16;
  public static final int Clase = 36;
  public static final int Potencia = 7;
  public static final int Selec = 31;
  public static final int Op_Incremento = 10;
  public static final int Asignacion = 11;
  public static final int Corchete_c = 19;
  public static final int Corchete_a = 18;
  public static final int Doble_comillas = 24;
  public static final int Op_Relacional = 12;
  public static final int Punto = 23;
  public static final int Car = 45;
  public static final int Vacio = 38;
  public static final int Para = 28;
  public static final int Flt = 42;
  public static final int Division = 5;
  public static final int Cadena = 53;
  public static final int Ejecutar = 39;
  public static final int Parentesis_c = 15;
  public static final int Publico = 35;
  public static final int Modulo = 6;
  public static final int Parentesis_a = 14;
  public static final int Op_Asignacion = 9;
  public static final int Hacer = 26;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int Romper = 34;
  public static final int Caso = 32;
  public static final int Comilla_simple = 25;
  public static final int ERROR = 54;
  public static final int Valor_Decimal = 46;
  public static final int Entc = 30;
  public static final int Dos_puntos = 22;
  public static final int Identificador = 48;
  public static final int Predet = 33;
  public static final int Si = 29;
  public static final int Punto_coma = 20;
  public static final int Resta = 3;
  public static final int Caracter = 52;
  public static final int Numero_Entero = 49;
  public static final int Valor_Booleano = 13;
  public static final int Dob = 43;
  public static final int Mientras = 27;
  public static final int Txt = 41;
  public static final int Ent = 40;
  public static final int Multiplicacion = 4;
  public static final int Suma = 2;
  public static final int Igual = 51;
  public static final int Valor_Flotante = 47;
  public static final int Bol = 44;
}

